version: '3'
services:
  staging-deps:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 5300
    image: kbespalyi/graphql-api-server
    ports:
      - "127.0.0.1:5300:5300"
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - PORT=5300
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27019/graphql-core-staging
    networks:
      - default
    depends_on:
      - redis
      - rabbitmq
      - mongo
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - 15672:15672
    hostname: rabbitmq
    networks:
      - default
  redis:
    image: redis
    networks:
      - default
  mongo:
    image: mongo:3.4.10
    ports:
      - 27017:27019
    networks:
      - default
  staging:
    image: node:9.1.0
    ports:
      - 4300:4300
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    networks:
      - default
    environment:
      - apiUrl=http://staging-deps
      - NODE_ENV=test
      - PORT=4300
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27019/graphql-core-staging
    command: npm run test-staging
  clean:
    extends:
      service: staging
    command: rm -rf node_modules
  install:
    extends:
      service: staging
    command: npm install --silent
