version: '3.2'

services:
  staging-deps:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 5300
    image: kbespalyi/graphql-api-server
    ports:
      - 80:5300
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - PORT=5300
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27019/graphql-core-staging
    deploy:
      replicas: 2
    networks:
      - graphql
    depends_on:
      - redis
      - rabbitmq
      - mongo
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - 15672:15672
    hostname: rabbitmq
    networks:
      - graphql
  redis:
    image: redis
    networks:
      - graphql
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27019
    networks:
      - graphql
  staging:
    image: node:12
    ports:
      - 4300:4300
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    networks:
      - default
    environment:
      - apiUrl=http://staging-deps
      - NODE_ENV=test
      - PORT=4300
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27019/graphql-core-staging
    command: npm run test-staging
#  clean:
#    extends:
#      service: staging
#    command: rm -rf node_modules
#  install:
#    extends:
#      service: staging
#    command: npm install --silent

networks:
  graphql:
