version: '2'
services:
  staging-deps:
    build:
      context: .
      dockerfile: Dockerfile.staging
      args:
        port: 5300
    image: server-graphql
    ports:
      - "127.0.0.1:5300:4300"
    expose:
      - "5300"
    environment:
      - NODE_ENV=staging
      - PORT=4300
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27019/graphql-core-staging
    networks:
      - default
    depends_on:
      - redis
      - rabbitmq
      - mongo
  rabbitmq:
    image: rabbitmq:3.6-management
    ports:
      - 15672:15672
    hostname: rabbitmq
    networks:
      - default
  redis:
    image: redis
    networks:
      - default
  mongo:
    image: mongo:3.4.10
    ports:
      - 27019:27019
    networks:
      - default
  staging:
    image: node:9.1.0
    ports:
      - 4200:5200
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    networks:
      - default
    environment:
      - apiUrl=http://staging-deps:5300
      - NODE_ENV=staging
      - PORT=4200
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27019/graphql-core-staging
    command: npm run start
  test:
    image: node:9.1.0
    ports:
      - 4100:5100
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    networks:
      - default
    environment:
      - NODE_ENV=test
      - PORT=4100
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://mongo:27017/graphql-core-staging
    command: npm run test
  clean:
    extends:
      service: staging
    command: rm -rf node_modules
  install:
    extends:
      service: staging
    command: npm run install
