version: 2
jobs:
   build:
     docker:
       - image: circleci/node:9.1.0
       - image: mongo:3.4.10
     steps:
       - checkout
       - setup_remote_docker:
         docker_layer_caching: true
       - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
       - restore_cache:
         keys:
           - dependency-cache-{{ checksum "package.json" }}
           - dependency-cache- # used if checksum fails
      - run:
        name: Install npm
        command: npm install
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - node_modules
  test:
    docker:
      - image: circleci/node:9.1.0
      - image: mongo:3.4.10
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - run:
          name: Generate code coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master
