name: Main workflow
on: [push]
jobs:
  run:
    name: Test on ${{matrix.node_version}}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        node_version: [8, 10, 12]
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@master
    - name: Set Node.js ${{matrix.node_version}}
      uses: actions/setup-node@master
      with:
        version: ${{matrix.node_version}}

    - name: npm install and test
      run: |
        npm install
        npm test
